# Generated by Django 5.0.6 on 2024-06-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_iphone_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='cor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='descricao',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='saude_bateria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
