# Generated by Django 5.0.6 on 2024-06-07 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_iphone_cor_alter_iphone_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
